[[main]]
  name = "Projects"
  url = "/projects/"
  weight = 10
  identifier = "projects"

[[main]]
  name = "The Moment"
  parent = "projects"
  url = "/projects/the-moment/"
  weight = 12

[[main]]
  name = "tsx_cmd"
  parent = "projects"
  url = "/projects/tsx-cmd/"
  weight = 11
  [main.params]
    draft = true

[[main]]
  name = "Lab Notes"
  url = "/lab-notes/"
  weight = 50

[[main]]
  name = "Prints"
  url = "/prints/"
  weight = 20
  [main.params]
    draft = true

[[main]]
  name = "Astro"
  url = "/astro/"
  weight = 30
  [main.params]
    draft = true

[[main]]
  name = "Models"
  url = "/models/"
  weight = 40
  [main.params]
    draft = true

[[main]]
  name = "Gallery"
  url = "/gallery/"
  weight = 45
  [main.params]
    draft = true

[[main]]
  name = "About"
  url = "/about/"
  weight = 60
